# This FunctionDescription example refers to the validate-video-face-recog function located in the repository folder
# testbed/workflows/face-detection/01-validate-video-face-recog

apiVersion: chunk-func.polaris-slo-cloud.github.io/v1
kind: FunctionDescription
metadata:
  namespace: func-test
  name: validate-video-face-recog
  labels:
    app.kubernetes.io/name: functiondescription
    app.kubernetes.io/instance: validate-video-face-recog
    app.kubernetes.io/part-of: chunk-func-controller
spec:
  functionDescription:
    functionName: validate-video-face-recog
    functionContainer: user-container
    maxResponseTimeMs: 4000
    typicalInputs:
      - sizeBytes: 345600 # 20s * 720p * 24fps
        message:
          input:
            url: http://10.152.183.26
            # This is a demo deployment, we don't care about the password here.
            user: 3IbgCHdvv7Yo82F4
            password: sEt8IXptcUK2n2dLpJyAnC6xbrHs3ZWP
            bucket: face-detection
            objectKey: people-walking-20s-720p.mp4
            objectSizeBytes: 345600

      - sizeBytes: 518400 # 20s * 1080p * 24fps
        message:
          input:
            url: http://10.152.183.26
            # This is a demo deployment, we don't care about the password here.
            user: 3IbgCHdvv7Yo82F4
            password: sEt8IXptcUK2n2dLpJyAnC6xbrHs3ZWP
            bucket: face-detection
            objectKey: people-walking-20s-1080p.mp4
            objectSizeBytes: 518400

      - sizeBytes: 864000 # 40s * 720p * 30fps
        message:
          input:
            url: http://10.152.183.26
            # This is a demo deployment, we don't care about the password here.
            user: 3IbgCHdvv7Yo82F4
            password: sEt8IXptcUK2n2dLpJyAnC6xbrHs3ZWP
            bucket: face-detection
            objectKey: workout-40s-720p.mp4
            objectSizeBytes: 864000

      - sizeBytes: 1080000 # 60s * 720p * 25fps
        message:
          input:
            url: http://10.152.183.26
            # This is a demo deployment, we don't care about the password here.
            user: 3IbgCHdvv7Yo82F4
            password: sEt8IXptcUK2n2dLpJyAnC6xbrHs3ZWP
            bucket: face-detection
            objectKey: society-1m-720p.mp4
            objectSizeBytes: 1080000

      - sizeBytes: 1296000 # 40s * 1080p * 30fps
        message:
          input:
            url: http://10.152.183.26
            # This is a demo deployment, we don't care about the password here.
            user: 3IbgCHdvv7Yo82F4
            password: sEt8IXptcUK2n2dLpJyAnC6xbrHs3ZWP
            bucket: face-detection
            objectKey: workout-40s-1080p.mp4
            objectSizeBytes: 1296000

      - sizeBytes: 1620000 #  60s * 1080p * 25fps
        message:
          input:
            url: http://10.152.183.26
            # This is a demo deployment, we don't care about the password here.
            user: 3IbgCHdvv7Yo82F4
            password: sEt8IXptcUK2n2dLpJyAnC6xbrHs3ZWP
            bucket: face-detection
            objectKey: society-1m-1080p.mp4
            objectSizeBytes: 1620000
