---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - chunk-func.polaris-slo-cloud.github.io
  resources:
  - functiondescriptions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - chunk-func.polaris-slo-cloud.github.io
  resources:
  - functiondescriptions/finalizers
  verbs:
  - update
- apiGroups:
  - chunk-func.polaris-slo-cloud.github.io
  resources:
  - functiondescriptions/status
  verbs:
  - get
  - patch
  - update
