//go:build !ignore_autogenerated

/*
Copyright 2023 Polaris SLO Cloud.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package function

import (
	"k8s.io/apimachinery/pkg/runtime"
	"knative.dev/serving/pkg/apis/serving/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionDescription) DeepCopyInto(out *FunctionDescription) {
	*out = *in
	if in.TypicalInputs != nil {
		in, out := &in.TypicalInputs, &out.TypicalInputs
		*out = make([]*FunctionInput, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(FunctionInput)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionDescription.
func (in *FunctionDescription) DeepCopy() *FunctionDescription {
	if in == nil {
		return nil
	}
	out := new(FunctionDescription)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionInput) DeepCopyInto(out *FunctionInput) {
	*out = *in
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionInput.
func (in *FunctionInput) DeepCopy() *FunctionInput {
	if in == nil {
		return nil
	}
	out := new(FunctionInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionWithDescription) DeepCopyInto(out *FunctionWithDescription) {
	*out = *in
	if in.Function != nil {
		in, out := &in.Function, &out.Function
		*out = new(v1.Service)
		(*in).DeepCopyInto(*out)
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(FunctionDescription)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionWithDescription.
func (in *FunctionWithDescription) DeepCopy() *FunctionWithDescription {
	if in == nil {
		return nil
	}
	out := new(FunctionWithDescription)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OptimizedFunctionConfig) DeepCopyInto(out *OptimizedFunctionConfig) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(ResourceConfiguration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OptimizedFunctionConfig.
func (in *OptimizedFunctionConfig) DeepCopy() *OptimizedFunctionConfig {
	if in == nil {
		return nil
	}
	out := new(OptimizedFunctionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProfilingResult) DeepCopyInto(out *ProfilingResult) {
	*out = *in
	if in.ResultType != nil {
		in, out := &in.ResultType, &out.ResultType
		*out = new(ProfilingResultType)
		**out = **in
	}
	if in.ExecutionCost != nil {
		in, out := &in.ExecutionCost, &out.ExecutionCost
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProfilingResult.
func (in *ProfilingResult) DeepCopy() *ProfilingResult {
	if in == nil {
		return nil
	}
	out := new(ProfilingResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProfilingSessionResults) DeepCopyInto(out *ProfilingSessionResults) {
	*out = *in
	if in.ProfilingStarted != nil {
		in, out := &in.ProfilingStarted, &out.ProfilingStarted
		*out = (*in).DeepCopy()
	}
	if in.Results != nil {
		in, out := &in.Results, &out.Results
		*out = make([]*ResourceProfileResults, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ResourceProfileResults)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProfilingSessionResults.
func (in *ProfilingSessionResults) DeepCopy() *ProfilingSessionResults {
	if in == nil {
		return nil
	}
	out := new(ProfilingSessionResults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceConfiguration) DeepCopyInto(out *ResourceConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceConfiguration.
func (in *ResourceConfiguration) DeepCopy() *ResourceConfiguration {
	if in == nil {
		return nil
	}
	out := new(ResourceConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceProfileResults) DeepCopyInto(out *ResourceProfileResults) {
	*out = *in
	if in.Results != nil {
		in, out := &in.Results, &out.Results
		*out = make([]*ProfilingResult, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ProfilingResult)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.UnfilteredResults != nil {
		in, out := &in.UnfilteredResults, &out.UnfilteredResults
		*out = make([]*ProfilingResult, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ProfilingResult)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceProfileResults.
func (in *ResourceProfileResults) DeepCopy() *ResourceProfileResults {
	if in == nil {
		return nil
	}
	out := new(ResourceProfileResults)
	in.DeepCopyInto(out)
	return out
}
